### ISSUE TITLE
GPIO not allocated

### ISSUE THREAD

**Issue by craigerl** [SirLefti/Python_ILI9486#2]
Hey, thanks for implementing the lgpio fixes....  following your new readme with on a Pi with bookworm,

pi@digipi:~/git/Python_ILI9486 $ .venv/bin/python image.py
/home/pi/git/Python_ILI9486/.venv/lib/python3.11/site-packages/RPi/GPIO/__init__.py:622: Warning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  warnings.warn(Warning(
Traceback (most recent call last):
  File "/home/pi/git/Python_ILI9486/image.py", line 18, in <module>
    lcd = LCD.ILI9486(dc=config.DC_PIN, rst=config.RST_PIN, spi=spi).begin()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/git/Python_ILI9486/ILI9486.py", line 117, in __init__
    GPIO.setup(self.__dc, GPIO.OUT)
  File "/home/pi/git/Python_ILI9486/.venv/lib/python3.11/site-packages/RPi/GPIO/__init__.py", line 704, in setup
    initial = _check(lgpio.gpio_read(_chip, gpio))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/git/Python_ILI9486/.venv/lib/python3.11/site-packages/lgpio.py", line 906, in gpio_read
    return _u2i(_lgpio._gpio_read(handle&0xffff, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/git/Python_ILI9486/.venv/lib/python3.11/site-packages/lgpio.py", line 461, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO not allocated'

**Comment by craigerl** [comment]
sorry, disregard, another process had the gpiochip0 open.. another "feature" of this huge transition to gpiod.   thanks again for the support, please close this.
